const Constants = {
 ADD_TODO :"ADD_TODO",      
 REMOVE_TODO: "REMOVE_TODO",
 TOGGLE_TODO:"TOGGLE_TODO",
 ADD_GOAL :"ADD_GOAL",
 REMOVE_GOAL:"REMOVE_GOAL",
 ADD_API_DATA:"ADD_API_DATA"
}

export {Constants}